### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by firmai** [jamesdellinger/ai_for_trading_nanodegree_alpha_research_multi_factor_modeling_project#1]
Hey man, I can't seem to find the data to replicate this repository. Would you be able to help me out, d.snow@@@live.com. Thanks in advance, and great solution!

**Comment by jamesdellinger** [comment]
Hi and thanks for checking the repo out! 

Equity pricing data comes from Zipline. i.e. `from zipline.pipeline.data import USEquityPricing`. If you install Zipline in your conda env you should be able to access it. 

Sector data came directly thru Udacity's project portal. i.e. `self.data = np.load('../../data/project_4_sector/data.npy')`. Unfortunately, in order to access this you'll need to be enrolled in the AI for Trading nanodegree.
